### ISSUE TITLE
React 17 has Error: Function components cannot be given refs. Attempts to access this ref will fail.

### ISSUE THREAD

**Issue by hmmhmmhm** [ooade/react-click-away-listener#51]
![스크린샷 2022-01-01 오후 8 10 50](https://user-images.githubusercontent.com/38493722/147849265-999422c4-360e-47ed-938e-b19a17581b29.png)

```bash
react-dom.development.js?61bb:67
Warning: Function components cannot be given refs.
Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

**Comment by ooade** [comment]
Hi, can you share the version of click-away listener you're using?

**Comment by hmmhmmhm** [comment]
@ooade Yup! I'm using 2.0.5 version

**Comment by ooade** [comment]
Please, can you also add steps to reproduce? Thanks 🙏

**Comment by hmmhmmhm** [comment]
@ooade 
https://codesandbox.io/s/react-17-forked-iwsi8?file=/src/App.js

**Comment by ooade** [comment]
That's actually the expected behaviour. [Would need to add to the readme for clarification]. If you're wrapping the clickaway listener on a React component, it needs its ref forwarded. You can either forward the prop like it should be or wrap the clickaway listener on a base element like a div or span.

Why? refs get the underlying element and with that, we can compare the element with other elements within the DOM to be able to figure out when to trigger `onClickAway`.

**Comment by ooade** [comment]
That's actually the expected behaviour. [Would need to add to the readme for clarification]. If you're wrapping the clickaway listener on a React component, it needs its ref forwarded. You can either forward the ref like it should be or wrap the clickaway listener on a base element like a div or span.

Why? refs get the underlying element and with that, we can compare the element with other elements within the DOM to be able to figure out when to trigger `onClickAway`.

**Comment by rishabh-ink** [comment]
> You can either forward the ref like it should be

I didn’t understand this. How do we do this? Can you share an example? Thanks!

**Comment by ooade** [comment]
@rishabh-ink This is it:

```jsx
const Button = React.forwardRef((props, ref) => <button ref={ref}>{props.children}</button>);
```
